version: 2
updates:
  # npm - Main project dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "sarks0"
    assignees:
      - "sarks0"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    groups:
      # Group Next.js and React updates together
      next-react:
        patterns:
          - "next"
          - "react"
          - "react-dom"
          - "@next/*"
      # Group TypeScript and type definitions
      typescript:
        patterns:
          - "typescript"
          - "@types/*"
      # Group Tailwind CSS and related
      tailwind:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
          - "autoprefixer"
          - "postcss"
      # Group testing dependencies
      testing:
        patterns:
          - "@testing-library/*"
          - "jest"
          - "@jest/*"
          - "vitest"
      # Group ESLint and Prettier
      linting:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@eslint/*"
          - "prettier"
      # Group animation libraries
      animation:
        patterns:
          - "framer-motion"
          - "@react-spring/*"
      # Group state management
      state-management:
        patterns:
          - "zustand"
          - "@tanstack/*"
      # Group build tools
      build-tools:
        patterns:
          - "@vercel/*"
          - "sharp"
          - "@swc/*"
      # Group all other dependencies
      misc-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "next"
          - "react*"
          - "@next/*"
          - "typescript"
          - "@types/*"
          - "tailwindcss"
          - "@tailwindcss/*"
          - "eslint*"
          - "@eslint/*"
          - "prettier"
          - "framer-motion"
          - "zustand"
          - "@vercel/*"
          - "@testing-library/*"
          - "jest"
          - "@jest/*"
          - "vitest"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "05:00"
    open-pull-requests-limit: 2
    reviewers:
      - "sarks0"
    assignees:
      - "sarks0"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      actions:
        patterns:
          - "*"