# Dependabot configuration for DeepSix
# Automatically creates pull requests to keep dependencies up-to-date

version: 2
updates:
  # Enable version and security updates for npm packages
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "/"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    reviewers:
      - "Sarks0"
    groups:
      # Group all minor and patch updates together
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "three"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@react-three/fiber"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@react-three/drei"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@cloudflare/next-on-pages"
        update-types: ["version-update:semver-major"]
    allow:
      - dependency-type: "all"

  # Enable updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    pull-request-branch-name:
      separator: "/"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"
    reviewers:
      - "Sarks0"