name = "deepsix-dashboard"
compatibility_date = "2024-09-06"
compatibility_flags = ["nodejs_compat", "nodejs_als"]
pages_build_output_dir = ".next"

# Environment variables for development
[vars]
NEXT_PUBLIC_APP_URL = "http://localhost:3000"

# Note: NASA_API_KEY should be set as a secret in Cloudflare Pages dashboard
# Use: wrangler secret put NASA_API_KEY

# Optional: Add KV namespace for caching
# [[kv_namespaces]]
# binding = "__NEXT_ON_PAGES__KV_SUSPENSE_CACHE"
# id = "your-kv-namespace-id"