name: Syntax & Code Quality Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  syntax-typescript:
    name: TypeScript & ESLint Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: TypeScript compiler check
        run: npm run type-check
      
      - name: ESLint check
        run: npm run lint

  syntax-json-yaml:
    name: JSON & YAML Syntax Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Validate JSON files
        run: |
          echo "Validating JSON syntax..."
          for file in $(find . -name "*.json" -not -path "./node_modules/*" -not -path "./.next/*" -not -path "./.git/*"); do
            if python -m json.tool "$file" > /dev/null 2>&1; then
              echo "✅ Valid: $file"
            else
              echo "❌ Invalid JSON in: $file"
              python -m json.tool "$file"
              exit 1
            fi
          done
      
      - name: Install yamllint
        run: pip install yamllint
      
      - name: Validate YAML files
        run: |
          echo "Validating YAML syntax..."
          yamllint -d relaxed .github/ || true

  syntax-markdown:
    name: Markdown Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: |
            **/*.md
            !node_modules/**
            !.next/**
        continue-on-error: true

  code-formatting:
    name: Code Formatting Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Prettier
        run: npm install --save-dev prettier
      
      - name: Check Prettier formatting
        run: |
          echo "Checking code formatting..."
          npx prettier --check "**/*.{js,jsx,ts,tsx,json,css,md}" \
            --ignore-path .gitignore \
            --ignore-path .prettierignore 2>/dev/null || echo "Some files need formatting"
        continue-on-error: true